# Generated by Django 2.2 on 2023-12-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BusesApp', '0001_initial'),
        ('PasajerosApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Hora_Viaje', models.TimeField()),
                ('Fecha_Viaje', models.DateField()),
                ('Destino', models.CharField(max_length=100)),
                ('Origen', models.CharField(max_length=100)),
                ('Numero_de_Asiento', models.PositiveIntegerField()),
                ('matricula', models.CharField(max_length=20)),
                ('tipo_de_bus', models.CharField(choices=[('Dos Pisos', 'Dos Pisos'), ('Un Piso', 'Un Piso')], max_length=10)),
                ('empresa', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('tipoPasajero', models.CharField(choices=[('Estudiante', 'Estudiante'), ('AdultoMayor', 'Adulto Mayor'), ('Frecuente', 'Frecuente'), ('Normal', 'Normal')], max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusesApp.Bus')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PasajerosApp.Pasajero')),
            ],
        ),
    ]
